{{- range $key, $val := $.Values.apps }}
{{- if $val.enabled }}
{{- if contains "cicd" $key }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
spec:
  destination:
    name: ''
    namespace: {{ $key }}
    server: 'https://kubernetes.default.svc'
  source:
{{- if $val.helm }}
    helm:
      valueFiles:
{{- range $val.helm.valueFiles }}
        - {{ . }}
{{- end }}
{{- end }}
    path: .
    repoURL: '{{ $.Values.helmRepoUrl }}'
    targetRevision: '{{ $val.branch }}'
  project: jump-app
  ignoreDifferences:
  - group: image.openshift.io
    kind: ImageStream
    jsonPointers:
      - /spec/tags
{{- else }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
spec:
  destination:
    name: ''
    namespace: {{ $key }}
    server: 'https://kubernetes.default.svc'
  source:
{{- if $val.helm }}
    helm:
      valueFiles:
{{- range $val.helm.valueFiles }}
        - {{ . }}
{{- end }}
{{- end }}
    path: .
    repoURL: '{{ $.Values.helmRepoUrl }}'
    targetRevision: '{{ $val.branch }}'
  project: jump-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false  
  ignoreDifferences:
  - group: config.openshift.io/v1
    kind: ClusterVersion
    jsonPointers:
      - /spec/clusterID
{{- end }}
{{- end }}
{{- end }}