---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-deployments-admin-view
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccount:jump-app-cicd:tekton-deployments-admin'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader