{{- range $key, $val := $.Values.global.apps }}
{{- $versions := ternary "v1 v2" "v1" $val.multiVersions.enabled }}
{{- if not $val.knative }}
{{- range $version := (split " " $versions) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $key }}
    version: {{ $version }}
  name: {{ $key }}-{{ $version }}
spec:
  replicas: {{ $val.replicas }}
  selector:
    matchLabels:
      app: {{ $key }}
  template:
    metadata:
      {{- if $.Values.istio.enabled }}
      annotations:
        sidecar.istio.io/inject: "true"
      {{- end }}
      labels:
        name: {{ $key }}-{{ $version }}
        app: {{ $key }}
        version: {{ $version }}
    spec:
      containers:
{{- if contains "v1" $version }}
  {{- if $val.imagerepo }}
      - image: {{ $val.imagerepo }}:{{ $val.imagetag }}
  {{- else }}
      - image: image-registry.openshift-image-registry.svc:5000/{{ $.Values.cicd.namespace }}/{{ $key }}:{{ $val.imagetag }}
  {{- end }}
{{- else if contains "v2" $version }}
  {{- if $val.imagerepo }}
      - image: {{ $val.imagerepo }}:{{ $val.multiVersions.imagetag }}
  {{- else }}
      - image: image-registry.openshift-image-registry.svc:5000/{{ $.Values.cicd.namespace }}/{{ $key }}:{{ $val.multiVersions.imagetag }}
  {{- end }}
{{- end }}
        imagePullPolicy: Always
        name: {{ $key }}-{{ $version }}
        ports:
        {{- range $keyport, $valport := $val.containerPorts }}
          - containerPort: {{ $valport.containerPort }}
            protocol: {{ $valport.protocol }}
        {{- end }}
        resources: {}
{{- if $val.envVars }}
        env:
        {{- range $keyenvvar, $valueenvvar := $val.envVars }}  
          - name: {{ $keyenvvar }}
            value: {{ $valueenvvar }}
        {{- end }}
        {{- if $val.backend }}
          {{- if $.Values.istio.enabled }}
          - name: REACT_APP_BACK
            value: https://{{ $val.backend }}-{{ $.Release.Namespace }}.{{ $.Values.global.appsDomain }}/jump
            {{- range $appkey, $appval := $.Values.global.apps }}
              {{- if $appval.frontSettings }}
          - name: {{ $appval.frontSettings.var }}
                {{- if $appval.knative }}
            value: http://{{ $appkey }}.{{ $.Release.Namespace }}.svc.cluster.local
                {{- else }}
            value: http://{{ $appkey }}:{{ $appval.frontSettings.port }}
                {{- end }}
              {{- end }}
            {{- end }}
          {{- else }}
          - name: REACT_APP_BACK
            value: https://{{ $val.backend }}-{{ $version }}-{{ $.Release.Namespace }}.{{ $.Values.global.appsDomain }}/jump
            {{- range $appkey, $appval := $.Values.global.apps }}
              {{- if $appval.frontSettings }}
          - name: {{ $appval.frontSettings.var }}
                {{- if $appval.knative }}
            value: http://{{ $appkey }}-{{ $version }}.{{ $.Release.Namespace }}.svc.cluster.local
                {{- else }}
            value: http://{{ $appkey }}-{{ $version }}:{{ $appval.frontSettings.port }}
                {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
