{{- range $key, $val := $.Values.global.apps }}
{{- $versions := ternary "v1 v2" "v1" $val.multiVersions.enabled }}
{{- range $version := (split " " $versions) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $key }}
    version: {{ $version }}
  name: {{ $key }}-{{ $version }}
spec:
  replicas: {{ $val.replicas }}
  selector:
    matchLabels:
      app: {{ $key }}
  template:
    metadata:
      {{- if $.Values.istio.enabled }}
      annotations:
        sidecar.istio.io/inject: "true"
      {{- end }}
      labels:
        name: {{ $key }}-{{ $version }}
        app: {{ $key }}
        version: {{ $version }}
    spec:
      containers:
{{- if contains "v1" $version }}
      - image: image-registry.openshift-image-registry.svc:5000/{{ $.Values.cicd.namespace }}/{{ $key }}:{{ $val.imagetag }}
{{- else if contains "v2" $version }}
      - image: image-registry.openshift-image-registry.svc:5000/{{ $.Values.cicd.namespace }}/{{ $key }}:{{ $val.multiVersions.imagetag }}
{{- end }}
        imagePullPolicy: Always
        name: {{ $key }}-{{ $version }}
        ports:
        {{- range $keyport, $valport := $val.containerPorts }}
          - containerPort: {{ $valport.containerPort }}
            protocol: {{ $valport.protocol }}
        {{- end }}
        resources: {}
{{- if $val.envVars }}
        env:
        {{- range $keyenvvar, $valueenvvar := $val.envVars }}  
          - name: {{ $keyenvvar }}
            value: {{ $valueenvvar }}
        {{- end }}
        {{- if $val.backend }}
            {{- if $.Values.istio.enabled }}
          - name: REACT_APP_BACK
            value: https://{{ $val.backend }}-{{ $.Release.Namespace }}.{{ $.Values.appsDomain }}/jump
          - name: REACT_APP_GOLANG
            value: http://back-golang:8442
          - name: REACT_APP_SPRINGBOOT
            value: http://back-springboot:8443
          - name: REACT_APP_PYTHON
            value: http://back-python:8444
            {{- else }}
          - name: REACT_APP_BACK
            value: https://{{ $val.backend }}-{{ $version }}-{{ $.Release.Namespace }}.{{ $.Values.appsDomain }}/jump
          - name: REACT_APP_GOLANG
            value: http://back-golang-{{ $version }}:8442
          - name: REACT_APP_SPRINGBOOT
            value: http://back-springboot-{{ $version }}:8443
          - name: REACT_APP_PYTHON
            value: http://back-python-{{ $version }}:8444
            {{- end }}
        {{- end }}
{{- end }}
{{- end }}
{{- end }}
