---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-deployments-admin
subjects:
  - kind: ServiceAccount
    name: tekton-deployments-admin
    namespace: {{ $.Values.cicd.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view