{{- range $key, $val := $.Values.global.apps }}
{{- $versions := ternary "v1 v2" "v1" $val.multiVersions.enabled }}
{{- if $val.knative }}
{{- range $version := (split " " $versions) }}
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    app: {{ $key }}
    version: {{ $version }}
    {{- if not $val.public }}
    networking.knative.dev/visibility: cluster-local
    {{- end }}
  name: {{ $key }}-{{ $version }}
spec:
  template:
    spec:
      timeoutSeconds: 300
      containerConcurrency: 0
      containers:
      {{- if contains "v1" $version }}
      - image: image-registry.openshift-image-registry.svc:5000/{{ $.Values.cicd.namespace }}/{{ $key }}:{{ $val.imagetag }}
      {{- else if contains "v2" $version }}
      - image: image-registry.openshift-image-registry.svc:5000/{{ $.Values.cicd.namespace }}/{{ $key }}:{{ $val.multiVersions.imagetag }}
      {{- end }}
        name: {{ $key }}-{{ $version }}
        ports:
        {{- range $keyport, $valport := $val.containerPorts }}
          - containerPort: {{ $valport.containerPort }}
            protocol: {{ $valport.protocol }}
        {{- end }}
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources: {}
{{- if $val.envVars }}
        env:
        {{- range $keyenvvar, $valueenvvar := $val.envVars }}  
          - name: {{ $keyenvvar }}
            value: {{ $valueenvvar }}
        {{- end }}
        {{- if $val.backend }}
            {{- if $.Values.istio.enabled }}
          - name: REACT_APP_BACK
            value: https://{{ $val.backend }}-{{ $.Release.Namespace }}.{{ $.Values.global.appsDomain }}/jump
          - name: REACT_APP_GOLANG
            value: http://back-golang:8442
          - name: REACT_APP_SPRINGBOOT
            value: http://back-springboot:8443
          - name: REACT_APP_PYTHON
            value: http://back-python:8444
            {{- else }}
          - name: REACT_APP_BACK
            value: https://{{ $val.backend }}-{{ $version }}-{{ $.Release.Namespace }}.{{ $.Values.global.appsDomain }}/jump
          - name: REACT_APP_GOLANG
            value: http://back-golang-{{ $version }}:8442
          - name: REACT_APP_SPRINGBOOT
            value: http://back-springboot-{{ $version }}:8443
          - name: REACT_APP_PYTHON
            value: http://back-python-{{ $version }}:8444
            {{- end }}
        {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
