{{- if $.Values.istio.enabled }}
{{- range $key, $val := $.Values.global.apps }}
{{- if $val.public }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $key }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
    {{- if not $.Values.grpc.enabled }}
        number: 80
        name: http
        protocol: HTTP
    {{- else }}
        number: 80
        name: grpc
        protocol: GRPC
    {{- end }}
      hosts:
      - {{ $key }}-{{ $.Release.Namespace }}.{{ $.Values.global.appsDomain }}
{{- end }}
{{- end }}
{{- end }}