{{- if $.Values.istio.enabled }}
{{- if $.Values.istio.mtls }}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
  {{- if $.Values.knative.enabled }}
    mode: PERMISSIVE
  {{- else}}
    mode: STRICT
  {{- end }}
{{- end }}
{{- end }}