{{- if $.Values.istio.enabled }}
{{- range $key, $val := $.Values.global.apps }}
{{- if not $val.knative }}
{{- if $val.public }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $key }}-{{ $.Release.Namespace }}
  namespace: {{ $.Values.istio.namespace }}
spec:
  host: {{ $key }}-{{ $.Release.Namespace }}.{{ $.Values.global.appsDomain }}
  to:
    kind: Service
    name: istio-ingressgateway
  tls:
    {{- if not $.Values.grpc.enabled }}
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    {{- else }}
    termination: passthrough 
    insecureEdgeTerminationPolicy: None
    {{- end }}
  port:
    targetPort: http2
{{- end }}
{{- end }}
{{- end }}
{{- end }}