{{- if $.Values.istio.enabled }}
---
apiVersion: maistra.io/v1
kind: ServiceMeshMember
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  controlPlaneRef:
    name: {{ $.Values.istio.controlplane }}
    namespace: {{ $.Values.istio.namespace }}
{{- end }}