{{- if $.Values.istio.enabled }}
---
apiVersion: maistra.io/v1
kind: ServiceMeshMember
metadata:
  name: default
spec:
  controlPlaneRef:
    name: basic
    namespace: {{ $.Values.istio.namespace }}
{{- end }}