{{- if $.Values.istio.enabled }}
{{- range $key, $val := $.Values.global.apps }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $key }}
  name: {{ $key }}
spec:
  ports:
  {{- range $keysrvport, $valsrvport := $val.servicePorts }}
    - name: {{ $keysrvport }}
      port: {{ $valsrvport.port }}
      protocol: {{ $valsrvport.protocol }}
      targetPort: {{ $valsrvport.targetPort }}
  {{- end }}   
  selector:
    app: {{ $key }}
{{- end }}
{{- end }}