##
# Jump App Microservices Chart values
##

# Istio Settings
istio: 
  enabled: false
  namespace: istio-system
  controlplane: basic
  mtls: true

# Knative Settings
knative: 
  enabled: false

# CICD Settings
cicd:
  namespace: jump-app-cicd

# Mongo Settings
mongodb:
  enabled: false

# Global variables
global:

  # Public domain where apps will be published
  appsDomain: apps.acidonpe.sandbox1736.opentlc.com

  apps:
    front-javascript:
      imagetag: develop
      multiVersions: 
        enabled: false
      replicas: 1
      envVars:
        APP_REF_NAME: jump-app
      containerPorts:
        http:
          containerPort: 3000
          protocol: TCP
      servicePorts:
        http-8080:
          port: 8080
          protocol: TCP
          targetPort: 3000
      public: true
      routeTargetPort: http-8080
      backend: back-golang
      # knative: true - NOT TESTED YET
    back-golang:
      imagetag: develop
      multiVersions: 
        enabled: true
        imagetag: develop
        v1Traffic: 50
        v2Traffic: 50
      replicas: 1
      envVars:
        APP_REF_NAME: jump-app
      containerPorts:
        http:
          containerPort: 8442
          protocol: TCP
      servicePorts:
        http-8442:
          port: 8442
          protocol: TCP
          targetPort: 8442
      public: true
      routeTargetPort: http-8442
      frontSettings:
        var: REACT_APP_GOLANG
        port: 8442
      # knative: true - NOT TESTED YET
    back-python:
      imagetag: develop
      multiVersions: 
        enabled: false
      replicas: 1
      envVars:
        APP_REF_NAME: jump-app
      containerPorts:
        http:
          containerPort: 8080
          protocol: TCP
      servicePorts:
        http-8444:
          port: 8444
          protocol: TCP
          targetPort: 8080
      public: false
      routeTargetPort: http-8444
      # knative: true
      frontSettings:
        var: REACT_APP_PYTHON
        port: 8444
    back-springboot:
      imagetag: develop
      multiVersions: 
        enabled: false
      replicas: 1
      envVars:
        APP_REF_NAME: jump-app
      containerPorts:
        http:
          containerPort: 8080
          protocol: TCP
        https:
          containerPort: 8443
          protocol: TCP
        service:
          containerPort: 8778
          protocol: TCP
      servicePorts:
        http-8080:
          port: 8080
          protocol: TCP
          targetPort: 8080
        http-8443:
          port: 8443
          protocol: TCP
          targetPort: 8443
        http-8778:
          port: 8778
          protocol: TCP
          targetPort: 8778
      public: false
      routeTargetPort: http-8443
      frontSettings:
        var: REACT_APP_SPRINGBOOT
        port: 8443
      # knative: true - NOT TESTED YET
    # back-quarkus:
    #   imagetag: develop
    #   multiVersions:
    #     enabled: false
    #   replicas: 2
    #   envVars:
    #     APP_REF_NAME: jump-app
    #   containerPorts:
    #     http:
    #       containerPort: 8080
    #       protocol: TCP
    #   servicePorts:
    #     http-8445:
    #       port: 8445
    #       protocol: TCP
    #       targetPort: 8080
    #   public: false
    #   routeTargetPort: http-8080
    #   knative: true
    #   frontSettings:
    #     var: REACT_APP_QUARKUS
    #     port: 8445