##
# Jump App Microservices Chart values
##

# Istio Settings
istio: 
  enabled: false
  namespace: istio-system
  controlplane: basic
  mtls: true

# Knative Settings
# WARNING -> gRPC and Knative enabled are not supported
knative: 
  enabled: false

# CICD Settings
cicd:
  namespace: jump-app-cicd

# GRPC Settings
# WARNING -> gRPC and Knative enabled are not supported
grpc:
  enabled: true

# Global variables
global:

  # Public domain where apps will be published
  appsDomain: apps.acidonpe.sandbox1736.opentlc.com

  apps:
    front-javascript:
      imagetag: develop
      multiVersions: 
        enabled: false
      replicas: 1
      envVars:
        APP_REF_NAME: jump-app
      containerPorts:
        http:
          containerPort: 3000
          protocol: TCP
      servicePorts:
        http-8080:
          port: 8080
          protocol: TCP
          targetPort: 3000
      public: true
      routeTargetPort: http-8080
      backend: back-golang
      # knative: true
    back-golang:
      imagetag: develop
      multiVersions: 
        enabled: false
      replicas: 1
      envVars:
        APP_REF_NAME: jump-app
      containerPorts:
        http:
          containerPort: 50051
          protocol: TCP
      servicePorts:
        tcp-50051:
          port: 50051
          protocol: TCP
          targetPort: 50051
      public: true
      routeTargetPort: tcp-50051
      frontSettings:
        var: REACT_APP_GOLANG
        port: 50051
    back-python:
      imagetag: develop
      multiVersions: 
        enabled: false
      replicas: 1
      envVars:
        APP_REF_NAME: jump-app
        PYTHONPATH: ./grpcserver
      containerPorts:
        http:
          containerPort: 50052
          protocol: TCP
      servicePorts:
        tcp-50052:
          port: 50052
          protocol: TCP
          targetPort: 50052
      public: false
      routeTargetPort: http-8444
      frontSettings:
        var: REACT_APP_PYTHON
        port: 50052
    back-springboot:
      imagetag: develop
      multiVersions: 
        enabled: false
      replicas: 1
      envVars:
        APP_REF_NAME: jump-app
      containerPorts:
        http:
          containerPort: 50053
          protocol: TCP
      servicePorts:
        tcp-50053:
          port: 50053
          protocol: TCP
          targetPort: 50053
      public: false
      routeTargetPort: http-8443
      frontSettings:
        var: REACT_APP_SPRINGBOOT
        port: 50053
