{{- range $key, $val := $.Values.global.apps }}
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: {{ $key }}-git-repo-dev
spec:
  type: git
  params:
  - name: url
    value: {{ $val.gitRepo }}
  - name: revision
    value: {{ $.Values.gitBranchDev }}
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: {{ $key }}-git-repo-pre
spec:
  type: git
  params:
  - name: url
    value: {{ $val.gitRepo }}
  - name: revision
    value: {{ $.Values.gitBranchPro }}
{{- end }}
