{{- range $key, $val := $.Values.global.apps }}
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
  name: pipelinerun-pipeline-{{ $key }}-build-pre
spec:
  serviceAccountName: {{ $.Values.sa }}
  params:
    - name: git-branch
      value: '{{ $.Values.gitBranchPro }}'
    - name: git-commit
      value: '{{ $.Values.gitBranchPro }}'
  resources:
    - name: source-repo
      resourceRef:
        name: {{ $key }}-git-repo-pre
  pipelineRef:
    name: pipeline-{{ $key }}-build
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
  name: pipelinerun-pipeline-{{ $key }}-build-dev
spec:
  serviceAccountName: {{ $.Values.sa }}
  params:
    - name: git-branch
      value: '{{ $.Values.gitBranchDev }}'
    - name: git-commit
      value: '{{ $.Values.gitBranchDev }}'
  resources:
    - name: source-repo
      resourceRef:
        name: {{ $key }}-git-repo-dev
  pipelineRef:
    name: pipeline-{{ $key }}-build
{{- end }}
