{{- range $type := .Values.pipeTypes }}
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-{{ $type }}-new-commit-test
spec:
  resources:
    inputs:
      - name: workspace
        type: git
        targetPath: git-app
  steps:
{{- if eq $type "nodejs"}}
    - name: npm-install
      image: node
      command:
        - /bin/sh
        - -c
      args:
        - npm install
      workingDir: /workspace/git-app
    - name: npm-test
      image: node
      command:
        - /bin/sh
        - -c
      args:
        - npm run test
      workingDir: /workspace/git-app
{{- end }}
{{- if eq $type "java"}}
    - name: mvn-package
      image: gcr.io/cloud-builders/mvn
      command:
        - /usr/bin/mvn
      args:
      - package
      workingDir: /workspace/git-app
{{- end }}
{{- if eq $type "python"}}
    - name: pip-install
      image: python
      command:
        - /bin/sh
        - -c
      args:
        - pip install -r requirements.txt
      workingDir: /workspace/git-app
    - name: python-test
      image: python
      command:
        - /bin/sh
        - -c
      args:
        - /tekton/home/.local/bin/pytest -v
      workingDir: /workspace/git-app
{{- end }}
{{- if eq $type "golang"}}
    - name: go-test
      image: golang
      command:
        - /bin/sh
        - -c
      args:
        - make test
      workingDir: /workspace/git-app
{{- end }}
{{- end }}
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-new-commit-start-build
spec:
  params:
    - name: buildconfig
      description: The name of the buildconfig
      type: string
  steps:
    - name: run-new-build
      image: quay.io/openshift/origin-cli:latest
      script: |
          #!/usr/bin/env bash
          oc start-build bc/"$(params.buildconfig)" -n {{ $.Release.Namespace }} -w