{{- range $key, $val := $.Values.global.apps }}
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: triggertemplate-{{ $key }}-build
spec:
  params:
    - name: giturl
    - name: gitbranch
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: {{ $key }}-git-repo-$(uid)
      spec:
        type: git
        params:
          - name: revision
            value: $(tt.params.gitbranch)
          - name: url
            value: $(tt.params.giturl)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-{{ $key }}-build-$(uid)
      spec:
        pipelineRef:
          name: pipeline-{{ $key }}-build
        resources:
          - name: source-repo
            resourceRef:
              name: {{ $key }}-git-repo-$(uid)
        params:
          - name: gitbranch  
            value: $(tt.params.gitbranch)
{{- end }}
