apiVersion: v2
name: jump-app-micros
description: A Helm chart to deploy JumpApp's Objects for Kubernetes
type: application

version: 0.1.0
appVersion: 0.1.16

mantainers:
  - name: Asier Cidon
    email: acidonpe@redhat.com
