{{- if $.Values.istio.enabled }}
{{- range $key, $val := $.Values.global.apps }}
{{- if $val.public }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $key }}-{{ $.Release.Namespace }}
  namespace: {{ $.Values.istio.namespace }}
spec:
  host: {{ $key }}-{{ $.Release.Namespace }}.{{ $.Values.appsDomain }}
  to:
    kind: Service
    name: istio-ingressgateway
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: http2
{{- end }}
{{- end }}
{{- end }}