{{- range $key, $val := $.Values.global.apps }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-{{ $key }}
spec:
  to:
    kind: Service
    name: el-listener-{{ $key }}-v1-deploy
  port:
    targetPort: http-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}